"""Versioned tolerance constants for the rule engine."""

TOLERANCES_VERSION = "v1"

PCD_TOL_MM = 0.1
CB_TOL_MM = 0.1

ET_OK_BAND_MM = 5
ET_INWARD_MAX_MM = 5
ET_OUTWARD_MAX_MM = 15
ET_HARD_LIMIT_MM = 25
ET_APPROVED_TOL_MM = 2.0

DIAMETER_TOL_IN = 0.1
WIDTH_TOL_IN = 0.1
DIAMETER_PLUS_MINUS_IN = 1.0
WIDTH_CONDITION_IN = 1.0
